### ISSUE TITLE
Suggestions for improvements

### ISSUE THREAD

**Issue by reisfmb** [enonic/app-google-analytics#13]
@poi33 

Thanks for the effort on writing the remaining docs. Sadly I couldn't make it run locally... not because of the docs (they are pretty good), but because my trial has expired on enonic cloud, so I couldn't have a domain to properly test the app. I'll ask Mikita to update my access, and then I'll test its features.

Regardless of that, here are some code suggestions. Feel free to ignore them (but I'll try to convince you that they are good suggestions):

1. Use html + thymeleaf instead of html in string

Since the html code is not huge, I can see why you did it like that. But IMO it is much more readable to have a .html file with [this](https://github.com/enonic/app-google-analytics/blob/main/src/main/resources/admin/widgets/analytics-report/analytics-report.js#L71) together with thymeleaf + models. Dong it like that also makes it easier to maintain and add new functionality if the html increases.

2. Usage of simple pure helper functions with proper name to better describe code

The [get](https://github.com/enonic/app-google-analytics/blob/main/src/main/resources/admin/widgets/analytics-report/analytics-report.js#L5) function does a bunch of things before returning the final HTML. I had to invest some time reading everything to understand what each block of code was doing. My suggestion to improve its readability would be to create pure functions to execute and return what you need, and by naming them properly, you can guide the developer that is reading the code to more easily understand what it is actually happening, and what are your intentions with the code. Here's what I mean in more details:

Instead of: 
```javascript
    if (app.config) {
        //TODO document key name + example
        if (app.config && app.config["ga.credentialPath"]) {
            // log.info(`CredentialPath: ${app.config["ga.credentialPath"]}`);
            credentialPath = app.config["ga.credentialPath"];
        } else {
            return ErrorResponse("No path to credentials found");
        }
    }
```

You could write:
```javascript
    getCredentialPath(app) {
        if(!app.config) throw new Error("No app config");

        if(!app.config["ga.credentialPath"]) throw new Error("No path to credentials found")

        return app.config["ga.credentialPath"];
    }
```

and use it together with other helper functions, all of them inside a try / catch:
```javascript
   try {
        // ...
        
        const credentialPath = getCredentialPath(app);
        const content = getContent(req.params);
        const contentType = getContentType(content._id); // "site" or "page"
        
        // ...
    } catch (error) {
        return ErrorResponse(error.message)
    }
```

3. Do the same as in 2 for `client.js` file.

That's it!

Besides that, IMO the code is clean, minimal, and I loved the icon :wink:

**Comment by poi33** [comment]
@reisfmb Create your own https tunnel aka site to test https://ngrok.com/
